flw       @f, @f, $i12
fsw       @f, @f, $i12
fmadd.s   @f, @f, @f, @f
fmsub.s   @f, @f, @f, @f
fnmsub.s  @f, @f, @f, @f
fnmadd.s  @f, @f, @f, @f
fadd.s    @f, @f, @f
fsub.s    @f, @f, @f
fmul.s    @f, @f, @f
fdiv.s    @f, @f, @f
fsqrt.s   @f, @f
fsgnj.s   @f, @f, @f
fsgnjn.s  @f, @f, @f
fsgnjx.s  @f, @f, @f
fmin.s    @f, @f, @f
fmax.s    @f, @f, @f
fcvt.w.s  @f, @f
fcvt.wu.s @f, @f
fmv.x.s   @f, @f
feq.s     @f, @f, @f
flt.s     @f, @f, @f
fle.s     @f, @f, @f
fclass.s  @f, @f
fcvt.s.w  @f, @f
fcvt.s.wu @f, @f
fmv.s.x   @f, @f
frcsr     @f
frrm      @f
frflags   @f
fscsr     @f, @f
fsrm      @f, @f
fsflags   @f, @f
fsrmi     @f, $i12
fsflagsi  @f, $i12
fcvt.l.s  @f, @f
fcvt.lu.s @f, @f
fcvt.s.l  @f, @f
fcvt.s.lu @f, @f
